services:
  - type: web
    name: viral-fluencer-backend
    env: python
    buildCommand: |
      apt-get update && apt-get install -y build-essential libffi-dev python3-dev
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
    startCommand: python app.py
